### ISSUE TITLE
Improve scenario with running Liberty containers with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/ci.docker#363]
When Liberty containers are run with `readOnlyRootFilesystem` security context set to true, it encounters permission issues due to files being generated at runtime. In particular at these locations:
- `/opt/ol/wlp/output`
- `/opt/ol/wlp/usr/servers/defaultServer/configDropins`

It's possible to use init containers and volume mounts to get around this. But investigate whether anything can be done at container image level to improve this scenario.

**Comment by DasJayYa** [comment]
Yeah would love to see improvements in this space.

@leochr would love to see a sample on how you worked around the problem using Init Containers.

**Comment by leochr** [comment]
@DasJayYa Here are the details on the workaround. As files can be written to volumes with readOnlyRootFileSystem, the basic idea is to attach an emptyDir volume type (which will be shared among the containers) and add the locations to write to as subpath and then mount them. The init container commands copy the initial set of files the image comes with (i.e. cache, server config)

```
      initContainers:
        - name: wlp-init
          command:
            - /bin/bash
          args:
            - '-c'
            - "cp -rvn /opt/ol/wlp/output /wlp/\n\tcp -rvn /opt/ol/wlp/usr/servers/defaultServer/configDropins /wlp/\n\t"
          volumeMounts:
            - name: scratch
              mountPath: /wlp/output
              subPath: wlp-output
            - name: scratch
              mountPath: /wlp/configDropins
              subPath: wlp-config-dropins
      containers:
        - name: app
          env:
            - name: LOG_DIR
              value: /output/logs
          volumeMounts:
            - name: scratch
              mountPath: /tmp
              subPath: tmp
            - name: scratch
              mountPath: /opt/ol/wlp/output
              subPath: wlp-output
            - name: scratch
              mountPath: /opt/ol/wlp/usr/servers/defaultServer/configDropins
              subPath: wlp-config-dropins
      volumes:
        - name: scratch
          emptyDir: {}
```
